/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_MEMBER_ACCESS_before_class
  Available Variables:
    ctx: Context_Expression_MEMBER_ACCESS_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      base: const ebm::ExpressionRef&
      member: const ebm::ExpressionRef&
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Expression_MEMBER_ACCESS_before) {
    using namespace CODEGEN_NAMESPACE;
    auto prop = ctx.get_field<"body.id.property_decl">(ctx.member);
    if (prop) {
        MAYBE(getter_decl, ctx.get_field<"func_decl">(prop->getter_function.id));
        MAYBE(base, ctx.visit(ctx.base));
        MAYBE(ident, ctx.identifier(ctx.member));
        auto parent_ident = ctx.identifier(prop->parent_format);
        std::string args;
        // if state variable, pass as is
        for (auto& param : getter_decl.params.container) {
            auto param_name = ctx.identifier(param);
            if (!args.empty()) {
                args += ", ";
            }
            args += param_name;
        }
        if (ctx.config().bool_mapped_func.contains(get_id(prop->getter_function.id))) {
            ident[0] = std::tolower(ident[0]);
        }
        if (prop->merge_mode != ebm::MergeMode::STRICT_TYPE) {
            return CODE(base.to_writer(), ".", ident, "(", args, ")");
        }
        return CODE("(*", base.to_writer(), ".", ident, "(", args, "))");
    }
    if (auto comp_getter = get_composite_field(ctx, ctx.member)) {
        if (auto comp = comp_getter->composite_getter()) {
            MAYBE(getter_decl, ctx.get_field<"func_decl">(comp->id));
            auto parent_ident = ctx.identifier(comp_getter->parent_struct);
            MAYBE(member_ident, ctx.identifier(ctx.member));
            MAYBE(base, ctx.visit(ctx.base));
            std::string args;
            // if state variable, pass as is
            for (auto& param : getter_decl.params.container) {
                auto param_name = ctx.identifier(param);
                if (!args.empty()) {
                    args += ", ";
                }
                args += param_name;
            }
            auto base_ = base.to_writer();
            if (ctx.get_field<"struct_decl.related_variant">(comp_getter->parent_struct)) {
                base_ = CODE(std::move(base_), ".", parent_ident);
            }
            if (ctx.config().bool_mapped_func.contains(get_id(comp->id))) {
                member_ident[0] = std::tolower(member_ident[0]);
            }
            return CODE(base_, ".", member_ident, "(", args, ")");
        }
    }
    MAYBE(member, ctx.get_field<"body.id">(ctx.member));
    if (auto type_ref = get_variant_member_from_field(ctx, from_weak(member))) {
        auto got = ctx.config().bulk_primitive.find(get_id(*type_ref));
        if (got != ctx.config().bulk_primitive.end()) {
            // self.x -> self.
            MAYBE(base, ctx.get_field<"body.base">(ctx.base));
            MAYBE(field, (ctx.get_field<physical_field>(*type_ref)));
            MAYBE(getter, field.composite_getter());
            auto getter_name = ctx.identifier(getter.id);
            MAYBE(base_str, ctx.visit(base));
            // TODO: cast to original field type
            MAYBE(original_type, ctx.get_field<"type">(ctx.member));
            MAYBE(type_str, ctx.visit(original_type));
            // currently, type_str must be integer type
            return CODE(type_str.to_writer(), " (", base_str.to_writer(), ".", getter_name, "())");
        }
        auto variant_hold = std::format("tmp{}", get_id(*type_ref));
        MAYBE(member, ctx.visit(ctx.member));
        return CODE(variant_hold, ".", member.to_writer());
    }
    return pass;
}
