/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: includes
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
namespace ebm2go {
    const ebm::FieldDecl* get_composite_field(auto&& ctx, auto target) {
        ebmgen::MappingTable& mapping = get_visitor(ctx).module_;
        const ebm::FieldDecl* comp = ebmgen::access_field<"body.id.field_decl">(mapping, target);
        if (!comp) {
            return nullptr;
        }
        auto comp_type = ebmgen::access_field<"composite_field_decl">(mapping, comp->composite_field());
        if (comp_type && (comp_type->kind == ebm::CompositeFieldKind::BULK_PRIMITIVE ||
                          comp_type->kind == ebm::CompositeFieldKind::PREFIXED_UNION_PRIMITIVE)) {
            return comp;
        }
        return nullptr;
    }

    constexpr auto physical_field = "body.id.struct_decl.related_variant.variant_desc.related_field.field_decl";

}  // namespace ebm2go