/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_READ_DATA_class
  Available Variables:
    ctx: Context_Statement_READ_DATA
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      read_data: const ebm::IOData&
        io_ref: StatementRef
        field: WeakStatementRef
        target: ExpressionRef
        data_type: TypeRef
        attribute: IOAttribute
          endian: Endian
          sign: bool
          is_peek: bool
          has_lowered_statement: bool
          has_offset: bool
          reserved: bool
          dynamic_ref: *StatementRef
        size: Size
          unit: SizeUnit
          ref: *ExpressionRef
          size: *Varint
        lowered_statement: *LoweredIOStatement
          lowering_type: LoweringIOType
          io_statement: LoweredStatementRef
        offset: *ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_READ_DATA) {
    using namespace CODEGEN_NAMESPACE;
    auto& rctx = ctx;
    if (auto low = rctx.read_data.lowered_statement()) {
        if (low->lowering_type == ebm::LoweringIOType::VECTORIZED_IO) {
            return rctx.visit(low->io_statement.id);
        }
    }
    if (auto cand = is_bytes_type(rctx, rctx.read_data.data_type)) {
        MAYBE(target, rctx.visit(rctx.read_data.target));
        MAYBE(size_str, get_size_str(rctx, rctx.read_data.size));
        auto io_ = rctx.identifier(rctx.read_data.io_ref);
        auto offset_val = CODE("0");
        if (auto offset = rctx.read_data.offset()) {
            MAYBE(offset_str, rctx.visit(*offset));
            offset_val = offset_str.to_writer();
        }
        MAYBE(layer_str, get_identifier_layer_str(rctx, from_weak(rctx.read_data.field)));
        layer_str = "\\\"" + layer_str + "\\\"";
        CodeWriter w;
        if (auto dyn_size = rctx.read_data.size.ref(); dyn_size && ctx.is(ebm::ExpressionKind::GET_REMAINING_BYTES, *dyn_size)) {
            // until eof
            w.writeln(target.to_writer(), " = (*", io_, ")[:]");
            w.writeln("*", io_, " = (*", io_, ")[:0]");
        }
        else {
            ctx.config().imports.insert("errors");
            w.writeln("if len(*", io_, ") < ", size_str, " {");
            w.indent_writeln("return errors.New(\"not enough data to read for field ", layer_str, "\")");
            w.writeln("}");
            if (cand == BytesType::vector) {
                w.writeln(target.to_writer(), " = (*", io_, ")[:", size_str, "]");
            }
            else if (cand == BytesType::array) {
                auto array_anno = ctx.get_field<"array_annotation">(rctx.read_data.data_type);
                if (array_anno && *array_anno != ebm::ArrayAnnotation::none) {
                    // assign and shift
                    // if target is nil, assign io_ else expand target
                    if (offset_val.to_string() == "0") {
                        w.writeln(target.to_writer(), " = (*", io_, ")[:", size_str, "]");
                    }
                    else if (futils::number::is_integer(offset_val.to_string())) {
                        w.writeln(target.to_writer(), " = ", target.to_writer(), "[:", offset_val, " + ", size_str, "]");
                    }
                    else {
                        w.writeln("if len(", target.to_writer(), ") == 0 {");
                        {
                            auto scope = w.indent_scope();
                            w.writeln(target.to_writer(), " = (*", io_, ")[:", size_str, "]");
                        }
                        w.writeln("} else {");
                        {
                            auto scope = w.indent_scope();
                            w.writeln(target.to_writer(), " = ", target.to_writer(), "[:", offset_val, " + ", size_str, "]");
                        }
                        w.writeln("}");
                    }
                    w.writeln("*", io_, " = (*", io_, ")[", size_str, ":]");
                    return w;
                }
                w.writeln("copy(", target.to_writer(), "[:], (*", io_, ")[:", offset_val, " + ", size_str, "])");
            }
            w.writeln("*", io_, " = (*", io_, ")[", size_str, ":]");
        }
        return w;
    }
    if (auto lw = rctx.read_data.lowered_statement()) {
        return rctx.visit(lw->io_statement.id);
    }
    return "/* not implemented read data */";
}
