/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Visitor_before
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
std::set<std::string_view> imports;
std::unordered_set<std::uint64_t> bulk_primitive;
std::unordered_set<std::uint64_t> any_variant;
std::unordered_map<std::uint64_t, std::uint64_t> any_cast_counter;
std::unordered_set<std::uint64_t> bool_mapped_func;
std::unordered_map<std::uint64_t, ArrayLengthInfo> array_length_setters;
std::unordered_set<std::uint64_t> array_length_set_done;
bool inner_prop_setter = false;
bool use_io_reader_writer = true;
bool append_io = false;
ebm::StatementRef current_io;
std::string encode_fn_name;
std::string decode_fn_name;

bool on_until_eof_loop = false;

std::vector<bool> no_heap_mode;
bool has_byte_io = false;

IOMode io_mode;