/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry
  Available variables:
    visitor: Visitor
    module_: MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(entry) {
    using namespace CODEGEN_NAMESPACE;
    auto& root = ctx.visitor.wm.root;
    MAYBE(entry_point, ctx.get_entry_point());
    MAYBE(result, ctx.visit(entry_point));
    root.write_unformatted(result.to_string());
    convert_location_info(ctx, result.to_writer());
    futils::wrap::cerr_wrap() << ctx.visitor.program_name << ": Code Generated\n";
    return {};
}