/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_TYPE_CAST_class
  Available Variables:
    ctx: Context_Expression_TYPE_CAST
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      cast_kind: const ebm::CastType&
      from_type: const ebm::TypeRef&
      source_expr: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_TYPE_CAST) {
    using namespace CODEGEN_NAMESPACE;
    CodeWriter w;

    MAYBE(source_expr_str, ctx.visit(ctx.source_expr));
    MAYBE(target_type_str, ctx.visit(ctx.type));
    if (ctx.config().func_style_cast) {
        w.write(target_type_str.to_writer(), "(", source_expr_str.to_writer(), ")");
    }
    else {
        w.write("(", target_type_str.to_writer(), ")", source_expr_str.to_writer());
    }
    return w;
}