/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_DEFAULT_VALUE
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_DEFAULT_VALUE) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.config().default_value_custom) {
        auto custom = ctx.config().default_value_custom(ctx);
        if (!custom) {
            if (!is_pass_error(custom.error())) {
                return ebmgen::unexpect_error(std::move(custom.error()));
            }
        }
        else {
            return custom;
        }
    }
    /*here to write the hook*/
    MAYBE(default_, get_default_value(ctx, ctx.type, ctx.config().default_value_option));
    return default_;
}