/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_SETTER_STATUS
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    setter_status: SetterStatus
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_SETTER_STATUS) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.config().setter_status_ok.size() == 0 && ctx.config().setter_status_failure.size() == 0) {
        return ctx.setter_status == ebm::SetterStatus::SUCCESS ? ctx.config().bool_true : ctx.config().bool_false;
    }
    return ctx.setter_status == ebm::SetterStatus::SUCCESS ? ctx.config().setter_status_ok : ctx.config().setter_status_failure;
}