/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_WRITE_DATA
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    io_statement: StatementRef
    target_expr: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Expression_WRITE_DATA function.
// We can use variables like `this` (for Visitor) and function parameters directly.
// This code is included within the visit_Expression_WRITE_DATA function.
// We can use variables like `this` (for Visitor) and function parameters directly.
return visit_Statement(*this, io_statement);