/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_BINARY_OP
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    bop: BinaryOp
    left: ExpressionRef
    right: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Expression_BINARY_OP function.
// We can use variables like `this` (for Visitor) and `bop`, `left`, `right` directly.
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_BINARY_OP) {
    using namespace CODEGEN_NAMESPACE;

    CodeWriter w;

    MAYBE(left_str, ctx.visit(ctx.left));
    MAYBE(right_str, ctx.visit(ctx.right));
    auto it = ctx.config().alt_binary_op.find(ctx.bop);
    if (it != ctx.config().alt_binary_op.end()) {
        w.write("(", left_str.to_writer(), " ", it->second, " ", right_str.to_writer(), ")");
    }
    else {
        w.write("(", left_str.to_writer(), " ", to_string(ctx.bop), " ", right_str.to_writer(), ")");
    }

    return w;
}