/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_LITERAL_BOOL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    bool_value: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
/*license*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_LITERAL_BOOL) {
    using namespace CODEGEN_NAMESPACE;
    return ctx.bool_value ? ctx.config().bool_true : ctx.config().bool_false;
}