/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_MAX_VALUE_class
  Available Variables:
    ctx: Context_Expression_MAX_VALUE
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      lowered_expr: const ebm::LoweredExpressionRef&
        id: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_MAX_VALUE) {
    using namespace CODEGEN_NAMESPACE;
    MAYBE(result, ctx.visit(ctx.lowered_expr.id));
    return result;
}
