/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_CONDITIONAL_STATEMENT
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    conditional_stmt: StatementRef
    target_stmt: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_CONDITIONAL_STATEMENT) {
    using namespace CODEGEN_NAMESPACE;
    MAYBE(target_str, ctx.visit(ctx.target_stmt));
    MAYBE(conditional_str, ctx.visit(ctx.conditional_stmt));
    MAYBE(w, ctx.get_writer());
    w.get().write(std::move(target_str.to_writer()));
    w.get().write(std::move(conditional_str.to_writer()));
    return ctx.identifier(ctx.target_stmt);
}