/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_SETTER_STATUS
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    setter_status: SetterStatus
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

ebm::Expression expr;
expr.body.kind = ebm::ExpressionKind::LITERAL_BOOL;
expr.body.bool_value(setter_status == ebm::SetterStatus::SUCCESS);
return visit_Expression(*this, expr);