/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_AS_ARG
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    target_expr: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_AS_ARG) {
    if (ctx.config().as_arg_visitor) {
        return ctx.config().as_arg_visitor(ctx);
    }
    return ctx.visit(ctx.target_expr);
}