/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_COMPOSITE_FIELD_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    composite_field_decl: CompositeFieldDecl
      fields: Block
        len: Varint
        container: std::vector<StatementRef>
      composite_type: TypeRef
      kind: CompositeFieldKind
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_COMPOSITE_FIELD_DECL) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.config().composite_field_decl_visitor) {
        MAYBE(res, ctx.config().composite_field_decl_visitor(ctx));
        return res;
    }
    return ctx.visit(ctx.composite_field_decl.fields);
}