/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_EXPRESSION
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    expression: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_EXPRESSION) {
    using namespace CODEGEN_NAMESPACE;
    auto writer_added = ctx.add_writer();
    MAYBE(r, ctx.visit(ctx.expression));
    MAYBE(got, ctx.get_writer());
    got.get().write(std::move(r.to_writer()));
    return std::move(got.get());
}