/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_RETURN
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
CodeWriter w;

if (!is_nil(value)) {
    auto add = add_writer();
    MAYBE(ret_val, visit_Expression(*this, value));
    MAYBE(got, get_writer());
    w.merge(std::move(got));
    w.writeln("return ", ret_val.to_writer());
}
else {
    w.writeln("return");
}

return w;