/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_APPEND
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    target: ExpressionRef
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_APPEND) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (ctx.config().append_visitor) {
        MAYBE(res, ctx.config().append_visitor(ctx));
        return res;
    }
    MAYBE(target_str, ctx.visit(ctx.target));
    MAYBE(value_str, ctx.visit(ctx.value));

    return CODELINE(target_str.to_writer(), ".", ctx.config().append_function, "(", value_str.to_writer(), ")", ctx.config().endof_statement);
}
