/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ENUM_MEMBER_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    enum_member_decl: EnumMemberDecl
      name: IdentifierRef
      enum_decl: StatementRef
      value: ExpressionRef
      string_repr: StringRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_ENUM_MEMBER_DECL) {
    using namespace CODEGEN_NAMESPACE;
    auto name = ctx.identifier();

    CodeWriter w;
    MAYBE(val, ctx.visit(ctx.enum_member_decl.value));

    w.writeln(name, " = ", val.to_writer(), ctx.config().enum_member_separator);
    return w;
}