/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_RETURN
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_RETURN) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    CodeWriter w;

    if (!is_nil(ctx.value)) {
        auto add = ctx.config().wm.add_writer();
        MAYBE(ret_val, ctx.visit(ctx.value));
        MAYBE(got, ctx.config().wm.get_writer());
        w.merge(std::move(got));
        w.writeln("return ", ret_val.to_writer(), ctx.config().endof_statement);
    }
    else {
        w.writeln("return", ctx.config().endof_statement);
    }

    return w;
}