/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_MATCH_STATEMENT
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    match_statement: MatchStatement
      target: ExpressionRef
      is_exhaustive: bool
      reserved: std::uint8_t
      branches: Block
        len: Varint
        container: std::vector<StatementRef>
      lowered_if_statement: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_MATCH_STATEMENT) {
    using namespace CODEGEN_NAMESPACE;
    return ctx.visit(ctx.match_statement.lowered_if_statement.id);
}