/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_LOOP_STATEMENT_class
  Available Variables:
    ctx: Context_Statement_LOOP_STATEMENT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      loop: const ebm::LoopStatement&
        loop_type: LoopType
        collection: *ExpressionRef
        condition: *Condition
          cond: ExpressionRef
        increment: *StatementRef
        init: *StatementRef
        item_var: *StatementRef
        body: StatementRef
        lowered_statement: LoweredStatementRef
        next_lowered_loop: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
/*license*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_LOOP_STATEMENT) {
    auto& loop = ctx.loop;
    if (!is_nil(loop.lowered_statement.id)) {
        return ctx.visit(loop.lowered_statement.id);
    }
    CodeWriter w;
    if (auto init = loop.init(); init && init->id.value() != 0) {
        MAYBE(init_s, ctx.visit(*init));
        w.write(init_s.to_writer());
    }
    std::optional<std::string> cond;
    CodeWriter condition_related;
    if (auto c = loop.condition()) {
        auto added = ctx.add_writer();
        MAYBE(expr, ctx.visit(c->cond));
        cond = std::move(expr.to_string());
        MAYBE(got, ctx.get_writer());
        condition_related = std::move(got);
        w.write(condition_related);
    }
    else {
        if (ctx.config().infinity_loop_keyword.empty()) {
            MAYBE(true_, get_bool_literal(ctx, true));
            cond = std::move(true_);
        }
    }

    if (cond) {
        if (ctx.config().use_brace_for_condition) {
            w.writeln(ctx.config().conditional_loop_keyword, " (", tidy_condition_brace(std::move(*cond)), ") ", ctx.config().begin_block);
        }
        else {
            w.writeln(ctx.config().conditional_loop_keyword, " ", tidy_condition_brace(std::move(*cond)), " ", ctx.config().begin_block);
        }
    }
    else {
        w.writeln(ctx.config().infinity_loop_keyword, " ", ctx.config().begin_block);
    }
    {
        auto body_indent = w.indent_scope();
        MAYBE(body, ctx.visit(loop.body));
        w.write(body.to_writer());
        if (auto iter = loop.increment()) {
            MAYBE(step, ctx.visit(*iter));
            w.write(step.to_writer());
        }
        w.write(condition_related);
    }
    w.writeln(ctx.config().end_block);

    return w;
}