/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_PARAMETER_DECL_class
  Available Variables:
    ctx: Context_Statement_PARAMETER_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      param_decl: const ebm::ParameterDecl&
        name: IdentifierRef
        param_type: TypeRef
        is_state_variable: bool
        reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_PARAMETER_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto name = ctx.identifier();
    MAYBE(type, ctx.visit(ctx.param_decl.param_type));
    if (ctx.config().field_name_prior_to_type) {
        return CODE(name, " ", type.to_writer());
    }
    else {
        return CODE(type.to_writer(), " ", name);
    }
}
