/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ENUM_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    enum_decl: EnumDecl
      name: IdentifierRef
      base_type: TypeRef
      members: Block
        len: Varint
        container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_ENUM_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (ctx.config().enum_decl_visitor) {
        MAYBE(res, ctx.config().enum_decl_visitor(ctx));
        return res;
    }

    auto name = ctx.identifier();

    CodeWriter w;

    w.writeln("enum ", name, " ", ctx.config().begin_block);
    {
        auto scope = w.indent_scope();
        MAYBE(block, ctx.visit(ctx.enum_decl.members));
        w.write(block.to_writer());
    }
    w.writeln(ctx.config().end_block, ctx.config().endof_enum_definition);
    return w;
}