/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ASSIGNMENT
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    previous_assignment: WeakStatementRef
    target: ExpressionRef
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
/*license*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_ASSIGNMENT) {
    using namespace CODEGEN_NAMESPACE;
    CodeWriter w;
    MAYBE(result_target, ctx.visit(ctx.target));
    auto add = ctx.add_writer();
    MAYBE(got, ctx.get_writer());
    MAYBE(result_value, ctx.visit(ctx.value));
    w.write(std::move(got));
    w.writeln(result_target.to_writer(), " = ", tidy_condition_brace(result_value.to_string()), ctx.config().endof_statement);
    return w;
}