/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_PROGRAM_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    block: Block
      len: Varint
      container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_PROGRAM_DECL) {
    using namespace CODEGEN_NAMESPACE;
    CodeWriter w;
    for (const auto& stmt : ctx.block.container) {
        MAYBE(stmt_code, ctx.visit(stmt));
        for (auto& toplevel : ctx.config().decl_toplevel) {
            w.writeln(toplevel);
        }
        ctx.config().decl_toplevel.clear();
        w.write(stmt_code.to_writer());
    }
    return w;
}