/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_VARIANT_class
  Available Variables:
    ctx: Context_Type_VARIANT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::TypeRef
      kind: const ebm::TypeKind&
      variant_desc: const ebm::VariantDesc&
        common_type: TypeRef
        members: Types
          len: Varint
          container: std::vector<TypeRef>
        related_field: WeakStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Type_VARIANT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (!is_nil(ctx.variant_desc.common_type)) {
        return ctx.visit(ctx.variant_desc.common_type);
    }
    auto enum_name = ctx.config().variant_prefix + std::format("{}", get_id(ctx.item_id));
    return Result(enum_name);
}
