/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_STRUCT_class
  Available Variables:
    ctx: Context_Type_STRUCT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::TypeRef
      kind: const ebm::TypeKind&
      id: const ebm::StatementRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Type_STRUCT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto name = ctx.identifier(ctx.id);
    return name;
}
