/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Visitor
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
bool use_brace_for_condition = true;
bool use_elif = false;
std::string bool_true = "true";
std::string bool_false = "false";
std::string setter_status_ok = "";
std::string setter_status_failure = "";
std::string struct_keyword = "struct";
std::string begin_block = "{";
std::string end_block = "}";
std::string empty_block_marker = "";
std::string default_object_brace = "{}";
std::string default_vector_brace = "[]";
std::string variable_define_keyword = "";
std::string immutable_variable_define_keyword = "";
std::string constant_define_keyword = "";
bool variable_with_type = true;
std::string variable_type_separator = ":";
std::map<ebm::BinaryOp, std::string> alt_binary_op;
std::map<ebm::UnaryOp, std::string> alt_unary_op;
std::string metadata_comment_prefix = "/*";
std::string metadata_comment_suffix = "*/";
std::string self_value = "this";
DefaultValueOption default_value_option;
std::string endof_statement = "";
std::string endof_struct_definition = "";
std::string endof_enum_definition = "";
std::string enum_member_separator = "";
std::string enum_member_accessor = ".";
std::string array_size_get_function = "len";
bool surrounded_array_size = false; /*true: len(x) false: x.len()*/
std::string append_function = "append";
std::string infinity_loop_keyword = "";
bool field_name_prior_to_type = false;
bool variable_name_prior_to_type = true;
std::string usize_type_name = "usize";
bool byte_aligned_int = true;
std::string uint_prefix = "u";
std::string uint_suffix = "";
std::string int_prefix = "i";
std::string int_suffix = "";
std::string function_define_keyword = "fn";
std::string encoder_return_type = "EncoderReturn";
std::string decoder_return_type = "DecoderReturn";
std::string encoder_input_type = "EncoderInput";
std::string decoder_input_type = "DecoderInput";
std::string property_setter_return_type = "bool";
bool forward_type_in_function_decl = false;
std::string function_return_type_separator = "->";
bool use_base_type_of_enum = false;
std::function<expected<Result>(Result elem_type, size_t len)> array_type_wrapper;
std::function<expected<Result>(Result elem_type)> vector_type_wrapper;
std::function<expected<Result>(Result typ, bool is_state_variable)> param_type_wrapper;
std::string variant_prefix = "Variant";
bool func_style_cast = true;

std::vector<CodeWriter> decl_toplevel;
bool on_assign = false;  // useful for expression generation
