/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before
  Available variables:
    *this: Visitor
    module_: MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
variable_define_keyword = "let";
endof_statement = ";";
self_value = "self";
enum_member_accessor = "::";
module_.register_default_prefix(ebm::StatementKind::STRUCT_DECL, "Struct");
use_brace_for_condition = false;
