/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_AS_ARG_before
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    main_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    target_expr: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
{
    auto typ = module_.get_type_kind(type);
    MAYBE(expr, module_.get_expression(target_expr));
    if (typ == ebm::TypeKind::ENCODER_INPUT ||
        typ == ebm::TypeKind::DECODER_INPUT) {
        if (auto id = expr.body.id(); id && module_.get_statement_kind(*id) == ebm::StatementKind::VARIABLE_DECL) {
            MAYBE(var, main_logic())
            return CODE("&mut ", var.to_writer());
        }
    }
}