/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_CAN_READ_STREAM
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    io_ref: StatementRef
    num_bytes: Size
      unit: SizeUnit
      ref: *ExpressionRef
      size: *Varint
    stream_type: StreamType
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
// {}.fill_buf(){}.map(|b| !b.is_empty()){}
auto io_ = module_.get_associated_identifier(io_ref);
MAYBE(num_bytes_, get_size_str(*this, num_bytes));
return CODE(io_, ".fill_buf().map(|b| b.len() >= ", num_bytes_, ")");
