/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ENUM_MEMBER_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    enum_member_decl: EnumMemberDecl
      name: IdentifierRef
      value: ExpressionRef
      string_repr: StringRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
auto ident = module_.get_identifier(enum_member_decl.name);
if (!ident) {
    return unexpect_error("identifier not found");
}
auto name = ident->body.data;

MAYBE(value_str, visit_Expression(*this, enum_member_decl.value));

return CODELINE(name, " = ", value_str.to_writer(), ",");
