/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_PROGRAM_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    block: Block
      len: Varint
      container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_PROGRAM_DECL) {
    CodeWriter w;

    for (auto& stmt_ref : ctx.block.container) {
        MAYBE(stmt, ctx.visit(stmt_ref));
        for (auto& custom_type : ctx.config().custom_types) {
            w.writeln(custom_type);
        }
        ctx.config().custom_types.clear();
        w.writeln(stmt.to_writer());
    }
    if (ctx.config().use_statements.size() > 0) {
        CodeWriter use_w;
        for (auto& use_stmt : ctx.config().use_statements) {
            use_w.writeln(use_stmt);
        }
        use_w.writeln();
        use_w.write(std::move(w));
        return use_w;
    }
    return w;
}