/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FIELD_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    field_decl: FieldDecl
      name: IdentifierRef
      field_type: TypeRef
      parent_struct: StatementRef
      is_state_variable: bool
      inner_composite: bool
      reserved: std::uint8_t
      composite_field: *StatementRef
      composite_getter: *LoweredStatementRef
      composite_setter: *LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_FIELD_DECL) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.field_decl.is_state_variable()) {
        return Result("");  // Ignore state variables
    }
    MAYBE(struct_members, struct_union_members(ctx, ctx.field_decl.field_type));

    if (struct_members.size() > 0) {
        for (auto& member : struct_members) {
            ctx.config().custom_types.push_back(member.to_writer());
        }
        auto enum_name = "Variant" + std::format("{}", get_id(ctx.field_decl.field_type));

        CodeWriter w;
        w.writeln("#[derive(Debug, Clone, PartialEq, Eq, Default)]");  // Add common derives including Default
        w.writeln("pub enum ", enum_name, " {");
        auto scope = w.indent_scope();
        int i = 0;
        w.writeln("#[default]");
        w.writeln("None,");
        MAYBE(members, ctx.get_field<"variant_desc">(ctx.field_decl.field_type));
        for (auto& member_type_ref : members.members.container) {
            MAYBE(type, ctx.visit(member_type_ref));
            w.writeln("V", std::format("{}", i), "(", type.to_writer(), "),");
            i++;
        }
        scope.execute();
        w.writeln("}");
        ctx.config().custom_types.push_back(std::move(w));
    }
    auto name = ctx.identifier();

    MAYBE(type, ctx.visit(ctx.field_decl.field_type));

    return CODELINE("pub ", name, ": ", type.to_writer(), ",");
}