/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FIELD_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    field_decl: FieldDecl
      name: IdentifierRef
      field_type: TypeRef
      parent_struct: StatementRef
      is_state_variable: bool
      reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
if (field_decl.is_state_variable()) {
    return Result("");  // Ignore state variables
}

auto name = module_.get_associated_identifier(item_id);

MAYBE(type, visit_Type(*this, field_decl.field_type));

return CODELINE("pub ", name, ": ", type.to_writer(), ",");
