/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_STRUCT_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    struct_decl: StructDecl
      name: IdentifierRef
      fields: Block
        len: Varint
        container: std::vector<StatementRef>
      encode_fn: StatementRef
      decode_fn: StatementRef
      is_recursive: bool
      is_fixed_size: bool
      has_related_variant: bool
      reserved: std::uint8_t
      related_variant: *TypeRef
      size: *Size
        unit: SizeUnit
        ref: *ExpressionRef
        size: *Varint
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
auto name = module_.get_identifier_or(item_id);

CodeWriter w;
w.writeln("pub struct ", name, " {");
{
    auto scope = w.indent_scope();
    for(auto& field : struct_decl.fields.container) {
        MAYBE(field_str, visit_Statement(*this, field));
        w.write(field_str.to_writer());
    }
}
w.writeln("}");
return w;
