/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_STRUCT
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: TypeRef
    kind: TypeKind
    id: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
auto name = module_.get_identifier_or(id);
return Result(name);
