/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_VARIANT
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: TypeRef
    kind: TypeKind
    common_type: TypeRef
    members: Types
      len: Varint
      container: std::vector<TypeRef>
    related_field: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
if (!is_nil(common_type)) {
    return visit_Type(*this, common_type);
}
auto enum_name = "Variant" + std::format("{}", get_id(item_id));

return Result(enum_name);