/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_VOID
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: TypeRef
    kind: TypeKind
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
return Result("()");