/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before_class
  Available Variables:
    ctx: Context_entry_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebmcodegen/stub/url.hpp"
DEFINE_VISITOR(entry_before) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    ctx.config().solver_name = "solver";
    ctx.config().program_decl_start_wrapper = [](Context_Statement_PROGRAM_DECL& ctx) {
        CodeWriter w;
        w.writeln("// Code generated by ebm2z3 at ", repo_url, ". Work in progress");
        w.writeln("import z3");
        return w;
    };
    ctx.config().param_visitor = [](Context_Statement_PARAMETER_DECL& ctx, Result) -> expected<Result> {
        CodeWriter w;
        auto original_name = ctx.identifier();
        auto var_name = ctx.config().current_ident(ctx, ctx.item_id);
        MAYBE(type, ctx.get(ctx.param_decl.param_type));
        if (type.body.kind == ebm::TypeKind::ARRAY || type.body.kind == ebm::TypeKind::VECTOR) {
            auto size = ctx.get_field<"body.size">(type.body.element_type());
            if (size) {
                w.writeln(var_name, " = z3.Array('", original_name, "', z3.BitVecSort(64), z3.BitVecSort(", std::to_string(size->value()), "))");
            }
        }
        else {
            auto size = type.body.size();
            if (size) {
                w.writeln(var_name, " = z3.BitVec('", original_name, "',", std::to_string(size->value()), " )");
            }
        }
        return w;
    };
    return pass;
}
