/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_STRUCT_DECL_class
  Available Variables:
    ctx: Context_Statement_STRUCT_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      struct_decl: const ebm::StructDecl&
        name: IdentifierRef
        fields: Block
          len: Varint
          container: std::vector<StatementRef>
        is_recursive: bool
        is_fixed_size: bool
        has_related_variant: bool
        has_encode_decode: bool
        has_functions: bool
        has_properties: bool
        reserved: std::uint8_t
        related_variant: *TypeRef
        size: *Size
          unit: SizeUnit
          ref: *ExpressionRef
          size: *Varint
        decode_fn: *StatementRef
        encode_fn: *StatementRef
        methods: *Block
          len: Varint
          container: std::vector<StatementRef>
        properties: *Block
          len: Varint
          container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebmcodegen/stub/util.hpp"
DEFINE_VISITOR(Statement_STRUCT_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto& js = ctx.config().json_output;
    auto field = js.object();
    if (!is_nil(ctx.struct_decl.name)) {
        auto name = ctx.identifier();
        field("name", name);
    }
    field("fields", [&] {
        auto item = js.array();
        handle_fields(ctx, ctx.struct_decl.fields, true, [&](ebm::StatementRef ref, auto) {
            expected<Result> result;
            item([&] {
                result = ctx.visit(ref);
            });
            return result;
        });
    });
    return {};
}
