/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before_class
  Available Variables:
    ctx: Context_entry_before
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(entry_before) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    ctx.config().uint_prefix = "bit<";
    ctx.config().uint_suffix = ">";
    ctx.config().int_prefix = "bit<";
    ctx.config().int_suffix = ">";
    ctx.config().byte_aligned_int = false;
    return pass;
}
