/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FIELD_DECL_before_class
  Available Variables:
    ctx: Context_Statement_FIELD_DECL_before
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      field_decl: const ebm::FieldDecl&
        name: IdentifierRef
        field_type: TypeRef
        parent_struct: StatementRef
        is_state_variable: bool
        inner_composite: bool
        reserved: std::uint8_t
        composite_field: *StatementRef
        composite_getter: *LoweredStatementRef
        composite_setter: *LoweredStatementRef
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_FIELD_DECL_before) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(members, struct_union_members(ctx, ctx.field_decl.field_type));
    for (auto& member : members) {
        ctx.config().decl_toplevel.push_back(member.to_writer());
    }
    return pass;
}
