/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_COMPOSITE_FIELD_DECL_class
  Available Variables:
    ctx: Context_Statement_COMPOSITE_FIELD_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      composite_field_decl: const ebm::CompositeFieldDecl&
        fields: Block
          len: Varint
          container: std::vector<StatementRef>
        composite_type: TypeRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_COMPOSITE_FIELD_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto len = ctx.composite_field_decl.fields.container.size();
    return {};
}
