// Code generated by json2cpp2
#pragma once
#include <cstdint>
#include <vector>
#include <array>
#include <optional>
#include <variant>
#include <string_view>

#include <binary/flags.h>
#include <binary/float.h>
#include <view/iovec.h>
#include <binary/number.h>
#include <error/error.h>
namespace bm2 {
    enum class HookFile {
        keyword = 0,
    };
    constexpr const char* to_string(HookFile e) {
        switch (e) {
            case HookFile::keyword:
                return "keywords.txt";
        }
        return "";
    }

    constexpr std::optional<HookFile> HookFile_from_string(std::string_view str) {
        if (str.empty()) {
            return std::nullopt;
        }
        if (str == "keywords.txt") {
            return HookFile::keyword;
        }
        return std::nullopt;
    }
}  // namespace bm2
