/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_MEMBER_ACCESS_before_class
  Available Variables:
    ctx: Context_Expression_MEMBER_ACCESS_before
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      base: const ebm::ExpressionRef&
      member: const ebm::ExpressionRef&
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Expression_MEMBER_ACCESS_before) {
    using namespace CODEGEN_NAMESPACE;
    auto param = ctx.get_field<"body.id.param_decl">(ctx.base);
    if (param && param->is_state_variable()) {
        MAYBE(base_str, ctx.visit(ctx.base));
        MAYBE(member_ident, ctx.identifier(ctx.member));
        CodeWriter w;
        w.write(base_str.to_writer(), "->", member_ident);
        return w;
    }
    MAYBE(body, ctx.get_field<"body.id">(ctx.member));
    if (auto type_ref = get_variant_member_from_field(ctx, body)) {
        MAYBE(base, ctx.visit(ctx.base));
        MAYBE(ident, ctx.identifier(*type_ref));
        MAYBE(member, ctx.visit(ctx.member));
        return CODE(base.to_writer(), ".", ident, ".", member.to_writer());
    }
    if (auto comp_getter = ctx.get_field<"body.id.field_decl">(ctx.member)) {
        auto comp_ref = ctx.get_field<"composite_field_decl">(comp_getter->composite_field());
        if (comp_ref && comp_ref->kind == ebm::CompositeFieldKind::BULK_PRIMITIVE) {
            if (auto comp = comp_getter->composite_getter()) {
                MAYBE(getter_decl, ctx.get_field<"func_decl">(comp->id));
                auto parent_ident = ctx.identifier(comp_getter->parent_struct);
                MAYBE(member_ident, ctx.identifier(ctx.member));
                auto getter_func_name = std::format(
                    "{}_get_{}",
                    parent_ident,
                    member_ident);
                MAYBE(base, ctx.visit(ctx.base));
                std::string args;
                // if state variable, pass as is
                for (auto& param : getter_decl.params.container) {
                    auto param_name = ctx.identifier(param);
                    if (!args.empty()) {
                        args += ", ";
                    }
                    args += param_name;
                }
                return CODE(getter_func_name, "(&", base.to_writer(), args.empty() ? "" : ", ", args, ")");
            }
        }
    }
    return pass;
}
