/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: includes
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include <optional>
#include "ebm/extended_binary_module.hpp"
namespace ebm2c {
    struct Field {
        ebm::StatementRef id;
    };

    struct Struct {
        ebm::StatementRef id;
        std::vector<Field> fields;
        std::optional<ebm::StatementRef> encode_function;
        std::optional<ebm::StatementRef> decode_function;
    };

    struct Union {
        ebm::TypeRef id;
        std::vector<Struct> variants;
    };

}  // namespace ebm2c
