/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FUNCTION_DECL_class
  Available Variables:
    ctx: Context_Statement_FUNCTION_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      func_decl: const ebm::FunctionDecl&
        name: IdentifierRef
        return_type: TypeRef
        params: Block
          len: Varint
          container: std::vector<StatementRef>
        parent_format: WeakStatementRef
        kind: FunctionKind
        property: *WeakStatementRef
        body: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_FUNCTION_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto name = ctx.identifier();
    MAYBE(ret_type, ctx.visit(ctx.func_decl.return_type));
    CodeWriter params;
    std::string func_prefix;
    std::string inline_prefix;
    CodeWriter w;

    if (!is_nil(ctx.func_decl.parent_format)) {
        auto ident = ctx.identifier(ctx.func_decl.parent_format);
        func_prefix = ident + "_";
        params.write(ident, "* self");
    }
    for (const auto& param_ref : ctx.func_decl.params.container) {
        MAYBE(param, ctx.visit(param_ref));
        if (!params.empty()) {
            params.write(", ");
        }
        params.write(param.to_writer());
    }

    if (ctx.func_decl.kind == ebm::FunctionKind::COMPOSITE_GETTER ||
        ctx.func_decl.kind == ebm::FunctionKind::COMPOSITE_SETTER ||
        ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_GETTER ||
        ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_SETTER) {
        if (ctx.func_decl.kind == ebm::FunctionKind::COMPOSITE_SETTER ||
            ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_SETTER) {
            func_prefix += "set_";
        }
        else {
            func_prefix += "get_";
        }
    }

    // first, traverse body to determine
    MAYBE(body, ctx.visit(ctx.func_decl.body));

    if (ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_GETTER) {
    }

    inline_prefix = "inline ";  // TODO: currently, generateing all functions in header

    w.write(inline_prefix, ret_type.to_writer(), " ", func_prefix, name, "(", params, ")");
    if (ctx.config().forward_decl) {
        w.writeln(ctx.config().endof_statement);
        return w;
    }
    w.writeln(" ", ctx.config().begin_block);
    {
        auto scope = w.indent_scope();
        w.write(body.to_writer());
    }
    w.writeln(ctx.config().end_block);
    return w;
}
