/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FUNCTION_DECL_class
  Available Variables:
    ctx: Context_Statement_FUNCTION_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      func_decl: const ebm::FunctionDecl&
        name: IdentifierRef
        return_type: TypeRef
        params: Block
          len: Varint
          container: std::vector<StatementRef>
        parent_format: WeakStatementRef
        kind: FunctionKind
        property: *WeakStatementRef
        body: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/util.hpp"

namespace CODEGEN_NAMESPACE {
    struct Traversal {
        TRAVERSAL_VISITOR_BASE_WITHOUT_FUNC(Traversal, BaseVisitor);
        std::string_view func_name;
        CodeWriter tmp;
        expected<void> visit(CODEGEN_CONTEXT(Expression_ADDRESS_OF) & ctx) {
            tmp.write("REACHING Expression_ADDRESS_OF");
            return {};
        }
        template <typename Ctx>
        expected<void> visit(Ctx&& ctx) {
            if (ctx.is_before_or_after()) {
                return pass;
            }
            if (!ctx.context_name.contains("Statement")) {
                return {};
            }
            if (std::string_view(ctx.context_name) == "Statement_MATCH_STATEMENT" &&
                func_name.contains("HighEdge")) {
                tmp.writeln("// OK? Visiting ", ctx.context_name);
            }
            tmp.writeln("// Visiting ", ctx.context_name);
            return traverse_children<void>(*this, std::forward<Ctx>(ctx));
        }
    };
    static_assert(HasVisitor<void, Traversal, CODEGEN_CONTEXT(Expression_ADDRESS_OF) &>);

}  // namespace CODEGEN_NAMESPACE

DEFINE_VISITOR(Statement_FUNCTION_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto name = ctx.identifier();
    MAYBE(ret_type, ctx.visit(ctx.func_decl.return_type));
    CodeWriter params;
    std::string func_prefix;
    std::string inline_prefix;
    CodeWriter w;

    if (!is_nil(ctx.func_decl.parent_format)) {
        auto ident = ctx.identifier(ctx.func_decl.parent_format);
        func_prefix = ident + "_";
        params.write(ident, "* self");
    }
    for (const auto& param_ref : ctx.func_decl.params.container) {
        MAYBE(param, ctx.visit(param_ref));
        if (!params.empty()) {
            params.write(", ");
        }
        params.write(param.to_writer());
    }

    if (ctx.func_decl.kind == ebm::FunctionKind::COMPOSITE_GETTER ||
        ctx.func_decl.kind == ebm::FunctionKind::COMPOSITE_SETTER ||
        ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_GETTER ||
        ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_SETTER) {
        if (ctx.func_decl.kind == ebm::FunctionKind::COMPOSITE_SETTER ||
            ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_SETTER) {
            func_prefix += "set_";
        }
        else {
            func_prefix += "get_";
        }
    }

    // first, traverse body to determine
    MAYBE(body, ctx.visit(ctx.func_decl.body));

    if (ctx.func_decl.kind == ebm::FunctionKind::PROPERTY_GETTER) {
        Traversal traversal{ctx.visitor};
        traversal.func_name = func_prefix;
        visit_Object<void>(traversal, ctx.func_decl.body);
        w.write(traversal.tmp);
    }

    inline_prefix = "inline ";  // TODO: currently, generateing all functions in header

    w.write(inline_prefix, ret_type.to_writer(), " ", func_prefix, name, "(", params, ")");
    if (ctx.config().forward_decl) {
        w.writeln(ctx.config().endof_statement);
        return w;
    }
    w.writeln(" ", ctx.config().begin_block);
    {
        auto scope = w.indent_scope();
        w.write(body.to_writer());
    }
    w.writeln(ctx.config().end_block);
    return w;
}
