/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_PARAMETER_DECL_after_class
  Available Variables:
    ctx: Context_Statement_PARAMETER_DECL_after
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      param_decl: const ebm::ParameterDecl&
        name: IdentifierRef
        param_type: TypeRef
        is_state_variable: bool
        reserved: std::uint8_t
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
      result: expected<Result>&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_PARAMETER_DECL_after) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.param_decl.is_state_variable()) {
        auto ident = ctx.identifier();
        ctx.module().directly_map_statement_identifier(ctx.item_id, std::format("(*{})", ident));
    }
    /*here to write the hook*/
    return pass;
}
