/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ERROR_REPORT_class
  Available Variables:
    ctx: Context_Statement_ERROR_REPORT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      error_report: const ebm::ErrorReport&
        message: StringRef
        arguments: Expressions
          len: Varint
          container: std::vector<ExpressionRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "escape/escape.h"
DEFINE_VISITOR(Statement_ERROR_REPORT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(msg, ctx.get(ctx.error_report.message));
    CodeWriter w;
    if (!ctx.flags().no_detailed_error) {
        w.writeln("SET_LAST_ERROR(\"", futils::escape::escape_str<std::string>(msg.body.data), "\");");
    }
    w.writeln("return -1;");
    return w;
}
