/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_INIT_CHECK_class
  Available Variables:
    ctx: Context_Statement_INIT_CHECK
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      init_check: const ebm::InitCheck&
        init_check_type: InitCheckType
        target_field: ExpressionRef
        expect_value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_INIT_CHECK) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_encode) {
        MAYBE(type, ctx.get_field<"body.type.instance">(ctx.init_check.target_field));
        if (type.body.kind == ebm::TypeKind::RECURSIVE_STRUCT) {
            MAYBE(target_txt, ctx.visit(ctx.init_check.target_field));
            CodeWriter w;
            w.writeln("if (!", target_txt.to_writer(), ") {");
            {
                auto scope = w.indent_scope();
                w.writeln("return -1;  /* field not initialized */");
            }
            w.writeln("}");
            return w;
        }
    }
    if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_decode) {
        return CODELINE("/* field init check for decode */");
    }
    /*here to write the hook*/
    return "";
}
