/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_BINARY_OP_class
  Available Variables:
    ctx: Context_Expression_BINARY_OP
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      bop: const ebm::BinaryOp&
      left: const ebm::ExpressionRef&
      right: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include <ebmcodegen/stub/ops_macros.hpp>
DEFINE_VISITOR(Expression_BINARY_OP) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(left, ctx.visit(ctx.left));
    MAYBE(right, ctx.visit(ctx.right));
    auto str_repr = std::format("({} {} {})", left.str_repr, to_string(ctx.bop), right.str_repr);
    auto op = BinaryOp_to_OpCode(ctx.bop);
    if (op == ebm::OpCode::NOP) {
        return ebmgen::unexpect_error("unsupported binary operation: {}", to_string(ctx.bop));
    }
    ctx.config().env.instructions.push_back(Instruction{
        .instr = {
            .op = op,
        },
        .str_repr = str_repr,
    });
    return Result{.str_repr = str_repr};
}
