/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_UNARY_OP_class
  Available Variables:
    ctx: Context_Expression_UNARY_OP
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      operand: const ebm::ExpressionRef&
      uop: const ebm::UnaryOp&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include <ebmcodegen/stub/ops_macros.hpp>
DEFINE_VISITOR(Expression_UNARY_OP) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(operand, ctx.visit(ctx.operand));
    auto str_repr = std::format("({} {})", to_string(ctx.uop), operand.str_repr);
    auto op = UnaryOp_to_OpCode(ctx.uop);
    if (op == ebm::OpCode::NOP) {
        return ebmgen::unexpect_error("unsupported unary operation: {}", to_string(ctx.uop));
    }
    ctx.config().env.instructions.push_back(Instruction{
        .instr = {
            .op = op,
        },
        .str_repr = str_repr,
    });
    return {};
}
