/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_LITERAL_INT_class
  Available Variables:
    ctx: Context_Expression_LITERAL_INT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      int_value: const ebm::Varint&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_LITERAL_INT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    return Result{.value = Value{ctx.int_value.value()}, .str_repr = std::to_string(ctx.int_value.value())};
}
