/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_DEFAULT_VALUE_class
  Available Variables:
    ctx: Context_Expression_DEFAULT_VALUE
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/util.hpp"
DEFINE_VISITOR(Expression_DEFAULT_VALUE) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (ctx.is(ebm::TypeKind::INT) || ctx.is(ebm::TypeKind::UINT)) {
        return Result{.value = Value{0}, .str_repr = "0"};
    }
    if (auto bytes = is_bytes_type(ctx, ctx.type); bytes) {
        if (bytes == BytesType::array) {
            MAYBE(t, ctx.get(ctx.type));
            MAYBE(size, t.body.length());
            return Result{Value{ValueKind::BYTES_ARRAY_ZERO, size.value()}, "<bytes_array_zero>"};
        }
    }
    auto k = ctx.get_kind(ctx.type);
    return unexpect_error("unsupported default value type: {}", k ? to_string(*k) : "unknown");
}
