/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_INDEX_ACCESS_class
  Available Variables:
    ctx: Context_Expression_INDEX_ACCESS
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      base: const ebm::ExpressionRef&
      index: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_INDEX_ACCESS) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(base, ctx.visit(ctx.base));
    MAYBE(index, ctx.visit(ctx.index));
    MAYBE(ref_base, base.as_reference());
    MAYBE(bs, ctx.config().env.index_access_base(ref_base));
    MAYBE(idx, index.as_value().get_int(ctx.config().env));
    auto index_access = ctx.config().env.register_index_access_array(&bs, idx);
    return Result{.value = Value{ValueKind::INDEX_ACCESS, index_access}, .str_repr = std::format("{}[{}]", base.str_repr, index.str_repr)};
}
