/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_ENUM_MEMBER_class
  Available Variables:
    ctx: Context_Expression_ENUM_MEMBER
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      enum_decl: const ebm::StatementRef&
      member: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Expression_ENUM_MEMBER) {
    using namespace CODEGEN_NAMESPACE;
    auto enum_decl = ctx.identifier(ctx.enum_decl);
    MAYBE(ident, ctx.identifier(ctx.member));
    ebm::Instruction inst{.op = ebm::OpCode::LOAD_MEMBER};
    ctx.config().env.add_instruction(std::move(inst), std::format("{}.{}", enum_decl, ident));
    /*here to write the hook*/
    return {};
}
