/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_SELF_class
  Available Variables:
    ctx: Context_Expression_SELF
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_SELF) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    ctx.config().env.instructions.push_back(Instruction{
        .instr = {
            .op = ebm::OpCode::LOAD_SELF,
        },
        .str_repr = "LOAD_SELF",
    });
    return Result{.value = ctx.config().env.self, .str_repr = "self"};
}
