/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_IF_STATEMENT_class
  Available Variables:
    ctx: Context_Statement_IF_STATEMENT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      if_statement: const ebm::IfStatement&
        condition: Condition
          cond: ExpressionRef
        then_block: StatementRef
        else_block: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_IF_STATEMENT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(cond_expr, ctx.visit(ctx.if_statement.condition.cond));
    ctx.config().env.instructions.push_back(Instruction{
        .instr = {
            .op = ebm::OpCode::JUMP_IF_FALSE,
        },
        .str_repr = std::format("if ({})", tidy_condition_brace(std::move(cond_expr.str_repr))),
    });
    auto current_instr_index = ctx.config().env.instructions.size() - 1;
    MAYBE(then_res, ctx.visit(ctx.if_statement.then_block));
    auto then_block_end_index = ctx.config().env.instructions.size();
    ebm::Instruction& jump_if_false_instr = ctx.config().env.instructions[current_instr_index].instr;
    ebm::JumpOffset jump_offset;
    MAYBE(offset, varint(then_block_end_index - current_instr_index));
    jump_offset.offset = offset;
    jump_if_false_instr.target(jump_offset);
    return {};
}
