/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ASSERT_class
  Available Variables:
    ctx: Context_Statement_ASSERT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      assert_desc: const ebm::AssertDesc&
        condition: Condition
          cond: ExpressionRef
        lowered_statement: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/util.hpp"
DEFINE_VISITOR(Statement_ASSERT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(res, ctx.visit(ctx.assert_desc.condition.cond));
    ctx.config().env.instructions.push_back(Instruction{
        .instr = {
            .op = ebm::OpCode::ASSERT,
        },
        .str_repr = std::format("assert({})", tidy_condition_brace(std::move(res.str_repr))),
    });
    return {};
}
