/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_IF_STATEMENT_class
  Available Variables:
    ctx: Context_Statement_IF_STATEMENT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      if_statement: const ebm::IfStatement&
        condition: Condition
          cond: ExpressionRef
        then_block: StatementRef
        else_block: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_IF_STATEMENT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(cond_expr, ctx.visit(ctx.if_statement.condition.cond));
    ctx.config().env.add_instruction({
                                         .op = ebm::OpCode::JUMP_IF_FALSE,
                                     },
                                     std::format("if ({}) {{", tidy_condition_brace(std::move(cond_expr.str_repr))));
    auto current_instr_index = ctx.config().env.access_instructions().size() - 1;
    MAYBE(then_res, ctx.visit(ctx.if_statement.then_block));
    auto then_block_end_index = ctx.config().env.access_instructions().size();
    auto insert_jump_if_false = [&]() -> expected<void> {
        ebm::Instruction& jump_if_false_instr = ctx.config().env.access_instructions()[current_instr_index].instr;
        ebm::JumpOffset jump_offset;
        MAYBE(offset, varint(then_block_end_index - current_instr_index));
        jump_offset.offset = offset;
        jump_if_false_instr.target(jump_offset);
        return {};
    };
    if (!is_nil(ctx.if_statement.else_block)) {
        ctx.config().env.add_instruction({.op = ebm::OpCode::JUMP}, "} else { ");
        insert_jump_if_false();
        auto jump_instr_index = ctx.config().env.access_instructions().size() - 1;
        MAYBE(else_res, ctx.visit(ctx.if_statement.else_block));
        auto else_block_end_index = ctx.config().env.access_instructions().size();
        ebm::Instruction& jump_instr = ctx.config().env.access_instructions()[jump_instr_index].instr;
        ebm::JumpOffset else_jump_offset;
        MAYBE(else_offset, varint(else_block_end_index - jump_instr_index));
        else_jump_offset.offset = else_offset;
        jump_instr.target(else_jump_offset);
    }
    else {
        insert_jump_if_false();
    }
    ctx.config().env.add_instruction({.op = ebm::OpCode::NOP}, "}");
    return {};
}
