/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_APPEND_class
  Available Variables:
    ctx: Context_Statement_APPEND
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      target: const ebm::ExpressionRef&
      value: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_APPEND) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(target, ctx.visit(ctx.target));
    MAYBE(value, ctx.visit(ctx.value));
    ctx.config().env.add_instruction({.op = ebm::OpCode::VECTOR_PUSH}, std::format("{}.append({})", target.str_repr, value.str_repr));
    return {};
}
