/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_READ_DATA_class
  Available Variables:
    ctx: Context_Statement_READ_DATA
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      read_data: const ebm::IOData&
        io_ref: StatementRef
        target: ExpressionRef
        data_type: TypeRef
        attribute: IOAttribute
          endian: Endian
          sign: bool
          is_peek: bool
          has_lowered_statement: bool
          reserved: std::uint8_t
          dynamic_ref: *StatementRef
        size: Size
          unit: SizeUnit
          ref: *ExpressionRef
          size: *Varint
        lowered_statement: *LoweredIOStatement
          lowering_type: LoweringIOType
          io_statement: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_READ_DATA) {
    using namespace CODEGEN_NAMESPACE;
    if (auto is_bytes = is_bytes_type(ctx, ctx.read_data.data_type)) {
        auto input = ctx.config().input;
    }
    return {};
}
