/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_RETURN_class
  Available Variables:
    ctx: Context_Statement_RETURN
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      related_function: const ebm::WeakStatementRef&
        id: StatementRef
      value: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_RETURN) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (is_nil(ctx.value)) {
        ctx.config().env.add_instruction({.op = ebm::OpCode::PUSH_NULL}, "<void>");
        ctx.config().env.add_instruction({.op = ebm::OpCode::RET}, "return");
        return {};
    }
    MAYBE(val, ctx.visit(ctx.value));
    ctx.config().env.add_instruction({.op = ebm::OpCode::RET}, std::format("return {}", val.str_repr));
    return {};
}