/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_VARIABLE_DECL_class
  Available Variables:
    ctx: Context_Statement_VARIABLE_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      var_decl: const ebm::VariableDecl&
        name: IdentifierRef
        var_type: TypeRef
        initial_value: ExpressionRef
        decl_kind: VariableDeclKind
        is_reference: bool
        reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_VARIABLE_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto ident = ctx.identifier();
    MAYBE(initial_value, ctx.visit(ctx.var_decl.initial_value));
    if (ctx.var_decl.is_reference()) {
        MAYBE(ref, initial_value.as_reference());
        ctx.config().env.define_reference(ident, ref);
    }
    else {
        ctx.config().env.define_variable(ident, initial_value.as_value());
    }
    return {};
}
