/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_RETURN_class
  Available Variables:
    ctx: Context_Statement_RETURN
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      value: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_RETURN) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (is_nil(ctx.value)) {
        ctx.config().env.instructions.push_back(Instruction{
            .instr = {
                .op = ebm::OpCode::PUSH_NULL,
            },
            .str_repr = "<void>",
        });
        ctx.config().env.instructions.push_back(Instruction{
            .instr = {
                .op = ebm::OpCode::RET,
            },
            .str_repr = "return",
        });
        return {};
    }
    MAYBE(val, ctx.visit(ctx.value));
    ctx.config().env.instructions.push_back(Instruction{
        .instr = {
            .op = ebm::OpCode::RET,
        },
        .str_repr = std::format("return {}", val.str_repr),
    });
    return {};
}
