/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_READ_DATA_class
  Available Variables:
    ctx: Context_Statement_READ_DATA
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        module_: ebmgen::MappingTable
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      read_data: const ebm::IOData&
        io_ref: StatementRef
        target: ExpressionRef
        data_type: TypeRef
        attribute: IOAttribute
          endian: Endian
          sign: bool
          is_peek: bool
          has_lowered_statement: bool
          reserved: std::uint8_t
          dynamic_ref: *StatementRef
        size: Size
          unit: SizeUnit
          ref: *ExpressionRef
          size: *Varint
        lowered_statement: *LoweredIOStatement
          lowering_type: LoweringIOType
          io_statement: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include <string>
#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_READ_DATA) {
    using namespace CODEGEN_NAMESPACE;
    if (auto lowered = ctx.read_data.lowered_statement()) {
        return ctx.visit(lowered->io_statement.id);
    }
    if (auto is_bytes = is_bytes_type(ctx, ctx.read_data.data_type)) {
        MAYBE(target, ctx.visit(ctx.read_data.target));
        ebm::Instruction instr;
        instr.op = ebm::OpCode::READ_BYTES;
        ebm::OptionalImmediateSize imm;
        std::string str_repr;
        if (auto size = ctx.read_data.size.size()) {
            imm.is_immediate(true);
            imm.size(*size);
            str_repr = std::format("read_bytes({}, {})", target.str_repr, size->value());
        }
        else if (auto ref = ctx.read_data.size.ref()) {
            MAYBE(size_expr, ctx.visit(*ref));
            str_repr = std::format("read_bytes({}, {})", target.str_repr, size_expr.str_repr);
        }
        instr.imm(imm);
        ctx.config().env.instructions.push_back(Instruction{
            .instr = instr,
            .str_repr = str_repr,
        });
        return Result{.str_repr = str_repr};
    }
    return {};
}
