/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Visitor
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
futils::view::rvec input;
size_t input_pos = 0;