/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry
  Available variables:
    *this: Visitor
    module_: MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
MAYBE(entry_point, module_.get_entry_point());
MAYBE(result, visit_Statement(*this, entry_point));
merge_result(*this, root, result);
futils::wrap::cerr_wrap() << program_name << ": Code Generated\n";