/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry
  Available variables:
    *this: Visitor
    module_: MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
MAYBE(entry_point, module_.get_entry_point());
MAYBE(result, visit_Statement(*this, entry_point));
root.write_unformatted(result.to_string());
convert_location_info(*this, result.to_writer());
futils::wrap::cerr_wrap() << program_name << ": Code Generated\n";