/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_ARRAY_SIZE
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    array_expr: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
MAYBE(array, visit_Expression(*this, array_expr));
if (visitor.surrounded_array_size) {
    return CODE(visitor.array_size_get_function, "(", array.to_writer(), ")");
}
else {
    return CODE(array.to_writer(), ".", visitor.array_size_get_function, "()");
}
