/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_LITERAL_TYPE
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionOp
    type_ref: TypeRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
return visit_Type(*this, type_ref);