/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_BINARY_OP
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    bop: BinaryOp
    left: ExpressionRef
    right: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Expression_BINARY_OP function.
// We can use variables like `this` (for Visitor) and `bop`, `left`, `right` directly.
CodeWriter w;

MAYBE(left_str, visit_Expression(*this, left));
MAYBE(right_str, visit_Expression(*this, right));
auto it = visitor.alt_binary_op.find(bop);
if (it != visitor.alt_binary_op.end()) {
    w.write("(", left_str.to_writer(), " ", it->second, " ", right_str.to_writer(), ")");
}
else {
    w.write("(", left_str.to_writer(), " ", to_string(bop), " ", right_str.to_writer(), ")");
}

return w;
