/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_ENUM_MEMBER
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    enum_decl: StatementRef
    member: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
auto enum_name = module_.get_identifier_or(enum_decl);
MAYBE(member_name, module_.get_identifier_or(member));
return CODE(enum_name, ".", member_name);