/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_CALL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    call_desc: CallDesc
      callee: ExpressionRef
      arguments: Expressions
        len: Varint
        container: std::vector<ExpressionRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Expression_CALL function.
// We can use variables like `this` (for Visitor) and `call_desc` directly.
CodeWriter w;

// Get the identifier name from call_desc.callee
MAYBE(callee, visit_Expression(*this, call_desc.callee));
w.write(callee.to_writer(), "(");
bool first = true;
for (auto& arg : call_desc.arguments.container) {
    MAYBE(arg_str, visit_Expression(*this, arg));
    if (!first) {
        w.write(",");
    }
    first = false;
    w.write(arg_str.to_writer());
}
w.write(")");
return w;