/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_CONDITIONAL_STATEMENT
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    conditional_stmt: StatementRef
    target_stmt: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

MAYBE(target_str, visit_Statement(*this, target_stmt));
MAYBE(conditional_str, visit_Statement(*this, conditional_stmt));
MAYBE(w, get_writer());
merge_result(*this, w, target_str);
merge_result(*this, w, conditional_str);
return module_.get_identifier_or(target_stmt);