/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_TYPE_CAST
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    cast_kind: CastType
    from_type: TypeRef
    source_expr: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
CodeWriter w;

MAYBE(source_expr_str, visit_Expression(*this, source_expr));
MAYBE(target_type_str, visit_Type(*this, type));
w.write(target_type_str.to_writer(), "(", source_expr_str.to_writer(), ")");

return w;