/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_DEFAULT_VALUE
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

MAYBE(default_, get_default_value(*this, type, visitor.default_value_option));
return default_;