/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_UNARY_OP
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    operand: ExpressionRef
    uop: UnaryOp
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

CodeWriter w;
MAYBE(right_str, visit_Expression(*this, operand));

auto it = this->alt_unary_op.find(uop);
if (it != this->alt_unary_op.end()) {
    w.write("(", it->second, " ", right_str.to_writer(), ")");
}
else {
    w.write("(", to_string(uop), " ", right_str.to_writer(), ")");
}
return w;
