/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_MEMBER_ACCESS
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    base: ExpressionRef
    member: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
/*license*/
MAYBE(base_str, visit_Expression(*this, base));
MAYBE(ident, module_.get_identifier(member));

return std::format("{}.{}", base_str.value, ident.body.data);