/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_READ_DATA
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    io_statement: StatementRef
    target_stmt: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Expression_READ_DATA function.
// We can use variables like `this` (for Visitor) and function parameters directly.
std::string ident = module_.get_associated_identifier(target_stmt);
MAYBE(define_variable, visit_Statement(*this, target_stmt));
MAYBE(io_logic, visit_Statement(*this, io_statement));
MAYBE(w, get_writer());
w.write(define_variable.to_writer());
w.write(io_logic.to_writer());
return ident;