/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_INDEX_ACCESS
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionOp
    base: ExpressionRef
    index: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

MAYBE(base_str, visit_Expression(*this, base));
MAYBE(index_str, visit_Expression(*this, index));

return std::format("{}[{}]", base_str.value, index_str.value);