/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Flags_struct
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
