/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Flags_bind
  Available variables:
    ctx: futils::cmdline::option::Context&
    lang_name: const char*
    lsp_name: const char*
    worker_name: const char*
    web_filtered: std::set<std::string>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
