/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_RETURN
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementOp
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
CodeWriter w;

if (!is_nil(value)) {
    auto add = add_writer();
    MAYBE(ret_val, visit_Expression(*this, value));
    w.writeln("return ", ret_val.value);
}
else {
    w.writeln("return");
}

return w.out();