/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_STRUCT_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementOp
    struct_decl: StructDecl
      name: IdentifierRef
      fields: Block
        len: Varint
        container: std::vector<StatementRef>
      encode_fn: StatementRef
      decode_fn: StatementRef
      is_recursive: bool
      reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/


auto name = module_.get_identifier_or(struct_decl.name, item_id);

CodeWriter w;

w.writeln("struct ", name, " {");
{
    auto scope = w.indent_scope();
    MAYBE(block, visit_Block(*this, struct_decl.fields));
    w.write_unformatted(block.value);
}
w.writeln("};");
return w.out();