/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_CONTINUE
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementOp
    continue_: LoopFlowControl
      related_statement: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
auto loop_ref = continue_.related_statement;
CodeWriter w;
while (!is_nil(loop_ref)) {
    MAYBE(loop_stmt, module_.get_statement(loop_ref));
    MAYBE(loop, loop_stmt.body.loop());
    if (auto iter = loop.increment()) {
        MAYBE(step, visit_Statement(*this, *iter));
        w.write_unformatted(step.value);
        break;
    }
    loop_ref = loop.lowered_statement.id;
}

w.writeln("continue");
return w.out();