/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_LOWERED_STATEMENTS
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    lowered_statements: LoweredStatements
      len: Varint
      container: std::vector<LoweredStatement>
        lowering_type: LoweringType
        statement: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
if (!lowered_statements.container.size()) {
    return unexpect_error("No lowered statements found");
}
return visit_Statement(*this, lowered_statements.container.back().statement);