/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ASSIGNMENT
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    previous_assignment: StatementRef
    target: ExpressionRef
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
/*license*/
CodeWriter w;
MAYBE(result_target, visit_Expression(*this, target));
MAYBE(result_value, visit_Expression(*this, value));

w.writeln(result_target.to_writer(), " = ", tidy_condition_brace(result_value.to_string()), endof_statement);
return w;
