/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_APPEND
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    target: ExpressionRef
    value: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

MAYBE(target_str, visit_Expression(*this, target));
MAYBE(value_str, visit_Expression(*this, value));

return CODELINE(target_str.to_writer(), ".", append_function, "(", value_str.to_writer(), ")", endof_statement);