/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_VARIABLE_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    var_decl: VariableDecl
      name: IdentifierRef
      var_type: TypeRef
      initial_value: ExpressionRef
      is_constant: bool
      is_reference: bool
      reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Statement_VARIABLE_DECL function.
// We can use variables like `this` (for Visitor) and `var_decl` directly.
CodeWriter w;
auto name = this->module_.get_identifier_or(item_id);
MAYBE(type_str_val, visit_Type(*this, var_decl.var_type));
std::optional<Result> initial_value;

if (!is_nil(var_decl.initial_value)) {
    auto add = add_writer();
    MAYBE(initial_value_, visit_Expression(*this, var_decl.initial_value));
    MAYBE(got, get_writer());
    w.write_unformatted(got.out());
    initial_value = initial_value_;
}
if (variable_define_keyword.size()) {
    w.write(variable_define_keyword, " ");
}
w.write(name);
if (initial_value) {
    w.write(" = ", initial_value->value);
}

w.writeln();

return w.out();