/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_STRUCT_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    struct_decl: StructDecl
      name: IdentifierRef
      fields: Block
        len: Varint
        container: std::vector<StatementRef>
      is_recursive: bool
      is_fixed_size: bool
      has_related_variant: bool
      has_encode_decode: bool
      has_functions: bool
      reserved: std::uint8_t
      related_variant: *TypeRef
      size: *Size
        unit: SizeUnit
        ref: *ExpressionRef
        size: *Varint
      decode_fn: *StatementRef
      encode_fn: *StatementRef
      methods: *Block
        len: Varint
        container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

auto name = module_.get_associated_identifier(item_id);

CodeWriter w;

w.writeln("struct ", name, " {");
{
    auto scope = w.indent_scope();
    MAYBE(block, visit_Block(*this, struct_decl.fields));
    w.write(block.to_writer());
}
w.writeln("};");
return w;