/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_COMPOSITE_FIELD_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    composite_field_decl: CompositeFieldDecl
      fields: Block
        len: Varint
        container: std::vector<StatementRef>
      composite_type: TypeRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
return visit_Block(*this, composite_field_decl.fields);