/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before
  Available variables:
    *this: Visitor
    module_: MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
begin_block = ":";
end_block = "";
use_brace_for_condition = false;
use_elif = true;
empty_block_marker = "pass";