/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before
  Available variables:
    *this: Visitor
    module_: MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

begin_block = ":";
end_block = "";
use_brace_for_condition = false;
use_elif = true;
empty_block_marker = "pass";
alt_binary_op = {
    {ebm::BinaryOp::logical_and, "and"},
    {ebm::BinaryOp::logical_or, "or"},
};
alt_unary_op = {
    {ebm::UnaryOp::logical_not, "not"},
};
metadata_comment_prefix = "#";
metadata_comment_suffix = "";
self_value = "self";
module_.register_default_prefix(ebm::StatementKind::STRUCT_DECL, "Struct");
module_.register_default_prefix(ebm::StatementKind::ENUM_DECL, "Enum");
module_.register_default_prefix(ebm::StatementKind::FUNCTION_DECL, "func");
module_.register_default_prefix(ebm::StatementKind::VARIABLE_DECL, "var");
module_.register_default_prefix(ebm::StatementKind::FIELD_DECL, "field");
module_.register_default_prefix(ebm::StatementKind::PARAMETER_DECL, "param");