/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_CONDITIONAL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    condition: ExpressionRef
    else_: ExpressionRef
    lowered_expr: LoweredExpressionRef
    then: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
MAYBE(cond_str, visit_Expression(*this, condition));
MAYBE(then_str, visit_Expression(*this, then));
MAYBE(else_str, visit_Expression(*this, else_));

return std::format("({} if {} else {})", then_str.to_string(), cond_str.to_string(), else_str.to_string());
