/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_WRITE_DATA
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    io_statement: StatementRef
    target_expr: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_WRITE_DATA) {
    MAYBE(statement_text, ctx.visit(ctx.io_statement));
    MAYBE(w, ctx.get_writer());
    w.get().write(statement_text.to_writer());
    return "";
}