/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_DEFAULT_VALUE_before
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

{
    MAYBE(type_body, module_.get_type(type));
    if (type_body.body.kind == ebm::TypeKind::PTR) {
        return "None";
    }
}