/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_DEFAULT_VALUE_before
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

{
    MAYBE(type_body, module_.get_type(type));
    if (type_body.body.kind == ebm::TypeKind::VARIANT) {
        return "None";
    }
    if (type_body.body.kind == ebm::TypeKind::ARRAY) {
        MAYBE(size, type_body.body.length());
        MAYBE(element_type, type_body.body.element_type());
        MAYBE(default_, as_DEFAULT_VALUE(*this, element_type));
        auto w = CODE("[", SEPARATED(", ", size.value(), default_.to_writer()), "]");
        if (is_u8(*this, element_type)) {
            return CODE("bytearray(", w, ")");
        }
        return w;
    }
}