/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_LITERAL_BOOL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    bool_value: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

return bool_value ? "True" : "False";
