/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_MEMBER_ACCESS_before
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    type: TypeRef
    kind: ExpressionKind
    base: ExpressionRef
    member: ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
{
    MAYBE(base_expr, module_.get_expression(base));
    if (base_expr.body.kind == ebm::ExpressionKind::IDENTIFIER && module_.get_statement_kind(*base_expr.body.id()) == ebm::StatementKind::ENUM_DECL) {
        MAYBE(base_str, visit_Expression(*this, base));
        MAYBE(ident, module_.get_identifier(member));
        return std::format("{}.{}.value", base_str.to_string(), ident.body.data);
    }
}