/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Flags
  Available variables:
    These are macros. Do not use other than these
    flag name format: long-name[,short-name,...] (e.g: "flag-name,f")
    DEFINE_FLAG(type,name,flag_name,flag_func,flag_func_args...)
    WEB_FILTERED(filtered_flag_names...)
    DEFINE_BOOL_FLAG(name,flag_name,help)
    DEFINE_STRING_FLAG(name,flag_name,help,arg_description)
    WEB_UI_NAME(ui_name)
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

DEFINE_BOOL_FLAG(async, false, "async", "use async for encoder/decoder");
WEB_UI_NAME("python2");