/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ENUM_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    enum_decl: EnumDecl
      name: IdentifierRef
      base_type: TypeRef
      members: Block
        len: Varint
        container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

auto name = module_.get_associated_identifier(item_id);

CodeWriter w;

w.writeln("class ", name, "(enum.IntEnum)", begin_block);
{
    auto scope = w.indent_scope();
    MAYBE(block, visit_Block(*this, enum_decl.members));
    merge_result(*this, w, block);
}
w.writeln(end_block);
return w;