/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Statement_FIELD_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementOp
    field_decl: FieldDecl
      name: IdentifierRef
      field_type: TypeRef
      parent_struct: StatementRef
      is_state_variable: bool
      reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Statement_FIELD_DECL function.
// We can use variables like `visitor` and `field_decl` directly.
CodeWriter w;
auto name = module_.get_identifier_or(field_decl.name, item_id, "field");
MAYBE(type_str_val, visit_Type(*this, field_decl.field_type));  // Correctly extract the string value

w.writeln(name, ": ", type_str_val.value, " = None");  // Use the extracted string value

return w.out();