/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FIELD_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    field_decl: FieldDecl
      name: IdentifierRef
      field_type: TypeRef
      parent_struct: StatementRef
      is_state_variable: bool
      reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
CodeWriter w;
auto name = module_.get_identifier_or(field_decl.name, item_id, "field");
MAYBE(type_str_val, visit_Type(*this, field_decl.field_type));  // Correctly extract the string value

w.writeln(name, ": ", type_str_val.to_string(), " = None");  // Use the extracted string value

return w.out();