/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Statement_STRUCT_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementOp
    struct_decl: StructDecl
      name: IdentifierRef
      fields: Block
        len: Varint
        container: std::vector<StatementRef>
      encode_fn: StatementRef
      decode_fn: StatementRef
      is_recursive: bool
      reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Statement_STRUCT_DECL function.
// We can use variables like `visitor` and `struct_decl` directly.
CodeWriter w;
auto name = this->module_.get_identifier_or(struct_decl.name, item_id, "Struct");

w.writeln("class ", name, ":");
auto scope = w.indent_scope();

for (auto& field_ref : struct_decl.fields.container) {
    MAYBE(field, this->module_.get_statement(field_ref));
    MAYBE(res, visit_Statement(*this, field));
    w.write_unformatted(res.value);
}

// Visit encode_fn if it exists
if (!is_nil(struct_decl.encode_fn)) {  // Corrected: Check value() of Varint id
    MAYBE(encode_fn_stmt, this->module_.get_statement(struct_decl.encode_fn));
    MAYBE(res, visit_Statement(*this, encode_fn_stmt));
    w.write_unformatted(res.value);
}

// Visit decode_fn if it exists
if (!is_nil(struct_decl.decode_fn)) {  // Corrected: Check value() of Varint id
    MAYBE(decode_fn_stmt, this->module_.get_statement(struct_decl.decode_fn));
    MAYBE(res, visit_Statement(*this, decode_fn_stmt));
    w.write_unformatted(res.value);
}

w.writeln();  // Add a blank line for readability.

return w.out();