CodeWriter w;
w.writeln("# Code generated by ebm2python at https://github.com/on-keyday/rebrgen");
w.writeln("import struct");
w.writeln();
MAYBE(d, visit_Block(*this, block));
w.write_unformatted(d);
return w.out();