/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_PROGRAM_DECL
  Available variables:
    *this: Visitor
    module_: MappingTable
    item_id: StatementRef
    kind: StatementKind
    block: Block
      len: Varint
      container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
CodeWriter w;
w.writeln("# Code generated by ebm2python at https://github.com/on-keyday/rebrgen");
w.writeln("import struct");
w.writeln("import enum");
w.writeln("from typing import Any, Union");
w.writeln();
MAYBE(d, visit_Block(*this, block));
w.write_unformatted(d.to_string());
return w.out();